type Language = 'es' | 'ca' | 'eu' | 'gl' | 'en';

const translations: Record<Exclude<Language, 'es'>, Record<string, string>> = {
  ca: { 'nav.home':'Inici', 'nav.fiestas':'Festes', 'nav.events':'Esdeveniments', 'nav.map':'Mapa', 'nav.participate':'Participa', 'nav.program':'Programa', 'hero.title':'Nou dies de tradició, música i alegria', 'hero.copy':'Torna a trobar-te amb El Pardo: activitats per gaudir en família, amb amistats i amb tot el barri.', 'hero.events':'Veure esdeveniments', 'hero.map':'Com arribar-hi', 'programme.label':'Agenda principal', 'programme.title':'Programa per dies', 'featured.label':'Una cita per a cada pla', 'featured.title':'No t’ho perdis…', 'events.label':'Consulta el programa', 'events.title':'Tots els esdeveniments', 'map.label':'Troba cada activitat', 'map.title':'On seran les activitats?', 'about.label':'El Pardo és comunitat', 'about.title':'Estimats pardenys', 'participate.label':'La teva opinió compta', 'participate.title':'Participa', 'participate.copy':'Ajuda’ns a continuar millorant el districte.', 'card.survey':'Enquesta oficial', 'card.idea':'Proposa la teva idea', 'card.incident':'Incidències', 'footer.tagline':'El teu districte, la teva comunitat.' },
  eu: { 'nav.home':'Hasiera', 'nav.fiestas':'Jaiak', 'nav.events':'Ekitaldiak', 'nav.map':'Mapa', 'nav.participate':'Parte hartu', 'nav.program':'Programa', 'hero.title':'Bederatzi egun tradizioz, musikaz eta alaitasunez', 'hero.copy':'El Pardo berriro ezagutu: familiarekin, lagunekin eta auzo osoarekin gozatzeko jarduerak.', 'hero.events':'Ikusi ekitaldiak', 'hero.map':'Nola iritsi', 'programme.label':'Agenda nagusia', 'programme.title':'Egunetako programa', 'featured.label':'Plan bakoitzerako hitzordua', 'featured.title':'Ez galdu…', 'events.label':'Kontsultatu programa', 'events.title':'Ekitaldi guztiak', 'map.label':'Aurkitu jarduera bakoitza', 'map.title':'Non izango dira jarduerak?', 'about.label':'El Pardo komunitatea da', 'about.title':'Pardeño maiteok', 'participate.label':'Zure iritziak balio du', 'participate.title':'Parte hartu', 'participate.copy':'Lagundu barrutia hobetzen jarraitzeko.', 'card.survey':'Inkesta ofiziala', 'card.idea':'Proposatu zure ideia', 'card.incident':'Gorabeherak', 'footer.tagline':'Zure barrutia, zure komunitatea.' },
  gl: { 'nav.home':'Inicio', 'nav.fiestas':'Festas', 'nav.events':'Eventos', 'nav.map':'Mapa', 'nav.participate':'Participa', 'nav.program':'Programa', 'hero.title':'Nove días de tradición, música e alegría', 'hero.copy':'Volve atoparte con El Pardo: actividades para gozar en familia, con amizades e con todo o barrio.', 'hero.events':'Ver eventos', 'hero.map':'Como chegar', 'programme.label':'Axenda principal', 'programme.title':'Programa por días', 'featured.label':'Unha cita para cada plan', 'featured.title':'Non o perdas…', 'events.label':'Consulta o programa', 'events.title':'Todos os eventos', 'map.label':'Atopa cada actividade', 'map.title':'Onde serán as actividades?', 'about.label':'El Pardo é comunidade', 'about.title':'Queridos pardeños', 'participate.label':'A túa opinión conta', 'participate.title':'Participa', 'participate.copy':'Axúdanos a seguir mellorando o distrito.', 'card.survey':'Enquisa oficial', 'card.idea':'Propón a túa idea', 'card.incident':'Incidencias', 'footer.tagline':'O teu distrito, a túa comunidade.' },
  en: { 'nav.home':'Home', 'nav.fiestas':'Festival', 'nav.events':'Events', 'nav.map':'Map', 'nav.participate':'Take part', 'nav.program':'Programme', 'hero.title':'Nine days of tradition, music and joy', 'hero.copy':'Meet El Pardo again: activities to enjoy with family, friends and the whole neighbourhood.', 'hero.events':'View events', 'hero.map':'Getting here', 'programme.label':'Main agenda', 'programme.title':'Daily programme', 'featured.label':'Something for every plan', 'featured.title':'Don’t miss…', 'events.label':'Browse the programme', 'events.title':'All events', 'map.label':'Find every activity', 'map.title':'Where will the activities take place?', 'about.label':'El Pardo is community', 'about.title':'Dear residents of El Pardo', 'participate.label':'Your opinion matters', 'participate.title':'Take part', 'participate.copy':'Help us keep improving the district.', 'card.survey':'Official survey', 'card.idea':'Share your idea', 'card.incident':'Report an issue', 'footer.tagline':'Your district, your community.' },
};

export function applyLanguage(language: Language) {
  document.documentElement.lang = language;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((element) => {
    const key = element.dataset.i18n!;
    const original = element.dataset.i18nDefault ?? element.textContent ?? '';
    element.dataset.i18nDefault = original;
    element.textContent = language === 'es' ? original : translations[language][key] ?? original;
  });
  window.localStorage.setItem('el-pardo-language', language);
}

export function savedLanguage(): Language {
  const value = window.localStorage.getItem('el-pardo-language');
  return value === 'ca' || value === 'eu' || value === 'gl' || value === 'en' ? value : 'es';
}
