type Language = 'es' | 'ca' | 'eu' | 'gl' | 'en';

const translations: Record<Exclude<Language, 'es'>, Record<string, string>> = {
  ca: {
    'incident.emergencyTitle':'Emergències:', 'incident.emergencyCopy':'si hi ha perill immediat per a persones o béns, truca al 112.', 'incident.emergencyBefore':'si hi ha perill immediat per a persones o béns, truca al ', 'incident.emergencyAfter':'.',
    'common.homeLink':'Tornar a l’inici de les festes', 'common.backToSite':'Tornar al web', 'common.backToParticipate':'Tornar a Participa', 'common.other':'Altre', 'common.location':'Barri o zona', 'common.email':'Correu electrònic', 'common.privacyInfo':'informació de privacitat',
    'idea.eyebrow':'La teva proposta', 'idea.title':'Proposa la teva idea', 'idea.description':'Comparteix una proposta concreta per millorar Fuencarral–El Pardo. L’equip municipal la rebrà per valorar-la.', 'idea.fieldTitle':'Títol de la proposta', 'idea.titlePlaceholder':'Ex.: Més ombra a la plaça', 'idea.area':'Àrea', 'idea.selectArea':'Selecciona una àrea', 'idea.publicSpace':'Espai públic', 'idea.culture':'Cultura i oci', 'idea.mobility':'Mobilitat', 'idea.environment':'Medi ambient', 'idea.youth':'Infància i joventut', 'idea.tellUs':'Explica’ns la teva idea', 'idea.descriptionPlaceholder':'Descriu què proposes, on tindria impacte i per què seria útil.', 'idea.emailOptional':'(opcional, només si vols resposta)', 'idea.consentBefore':'He llegit la ', 'idea.consentAfter':' i consento el tractament de la meva proposta.', 'idea.submit':'Enviar proposta',
    'incident.eyebrow':'Comunica una incidència', 'incident.title':'Incidències', 'incident.description':'Indica els problemes que trobis al barri perquè es puguin revisar. No facis servir aquest canal per a urgències: truca al 112.', 'incident.emergency':'Emergències: si hi ha perill immediat per a persones o béns, truca al 112.', 'incident.type':'Tipus d’incidència', 'incident.selectCategory':'Selecciona una categoria', 'incident.cleaning':'Neteja', 'incident.lighting':'Enllumenat', 'incident.road':'Via pública', 'incident.furniture':'Mobiliari urbà', 'incident.green':'Zones verdes', 'incident.noise':'Soroll', 'incident.location':'Ubicació', 'incident.locationPlaceholder':'Carrer, plaça o punt de referència', 'incident.describe':'Descriu la incidència', 'incident.descriptionPlaceholder':'Explica què passa i afegeix detalls que ajudin a localitzar-la.', 'incident.emailOptional':'(opcional, només si necessites resposta)', 'incident.consentBefore':'He llegit la ', 'incident.consentAfter':' i consento el tractament d’aquesta incidència.', 'incident.submit':'Enviar incidència',
    'brand.district':'Districte', 'language.label':'Idioma', 'nav.home':'Inici', 'nav.fiestas':'Festes', 'nav.events':'Esdeveniments', 'nav.map':'Mapa', 'nav.participate':'Participa', 'nav.program':'Programa',
    'hero.dates':'29 agost — 6 setembre 2026', 'hero.title':'Nou dies de tradició, música i alegria', 'hero.copy':'Torna a trobar-te amb El Pardo: activitats per gaudir en família, amb amistats i amb tot el barri.', 'hero.events':'Veure esdeveniments', 'hero.map':'Com arribar-hi', 'countdown.copy':'Falten per a l’inici de les festes', 'countdown.days':'dies',
    'programme.label':'Agenda principal', 'programme.title':'Programa per dies', 'programme.download':'Descarregar programa', 'programme.more':'Més informació', 'featured.label':'Una cita per a cada pla', 'featured.title':'No t’ho perdis…',
    'events.label':'Consulta el programa', 'events.title':'Tots els esdeveniments', 'events.count':'44 activitats', 'events.filters':'Filtres del programa', 'events.searchLabel':'Cercar esdeveniments', 'events.searchPlaceholder':'Cercar esdeveniments…', 'events.filterByCategory':'Filtrar per categoria', 'events.empty':'No hi ha activitats que coincideixin amb la cerca.',
    'map.label':'Troba cada activitat', 'map.title':'On seran les activitats?', 'map.copy':'Consulta al mapa tots els espais on se celebraran les festes, des dels jardins fins a les places i les carpes del Real Sitio.', 'map.open':'Obrir el mapa',
    'about.label':'El Pardo és comunitat', 'about.title':'Estimats pardenys', 'about.copyOne':'Les Festes del Real Sitio ens reuneixen per gaudir de la música, la cultura, l’esport i les tradicions que donen vida al nostre districte.', 'about.copyTwo':'Gràcies a la col·laboració d’associacions, entitats i veïnat, celebrem un programa pensat per a totes les edats.',
    'participate.label':'La teva opinió compta', 'participate.title':'Participa', 'participate.copy':'Ajuda’ns a continuar millorant el districte.', 'card.survey':'Enquesta oficial', 'card.surveyCopy':'Comparteix la teva opinió sobre les festes.', 'card.idea':'Proposa la teva idea', 'card.ideaCopy':'Comparteix propostes per millorar el districte.', 'card.incident':'Incidències', 'card.incidentCopy':'Comunica incidències al teu barri fàcilment.',
    'qr.label':'Enquesta oficial', 'qr.title':'Respon des del mòbil', 'qr.copy':'Escaneja el codi QR per obrir l’enquesta oficial de les festes d’El Pardo.', 'qr.open':'Obrir enquesta de Google', 'footer.tagline':'El teu districte, la teva comunitat.', 'footer.legalLinks':'Enllaços legals', 'footer.contact':'Contacte', 'footer.legal':'Avís legal', 'footer.privacy':'Privacitat', 'footer.accessibility':'Accessibilitat',
    'category.Todos':'Tots', 'category.Música':'Música', 'category.Infantil':'Infantil', 'category.Deportes':'Esports', 'category.Tradición':'Tradició', 'category.Cultura':'Cultura', 'category.Gastronomía':'Gastronomia', 'weekday.Sábado':'Dissabte', 'weekday.Domingo':'Diumenge', 'weekday.Lunes':'Dilluns', 'weekday.Martes':'Dimarts', 'weekday.Miércoles':'Dimecres', 'weekday.Jueves':'Dijous', 'weekday.Viernes':'Divendres', 'month.Agosto':'Agost', 'month.Septiembre':'Setembre',
    'event.dardos.title':'Torneig de dards', 'event.disco.title':'Discoteca mòbil', 'event.pregón.title':'Pregó de festes', 'event.orquesta.title':'Orquestra Tierra', 'event.carrera.title':'Cursa popular', 'event.chocolate.title':'Xocolatada popular', 'event.visita.title':'Visita guiada: Emilio Carrère', 'event.chapas.title':'Torneig infantil de xapes', 'event.procesión.title':'Processó solemne', 'event.gincana.title':'Gimcana amb jocs tradicionals', 'event.chinchon.title':'Torneig de chinchón', 'event.roxell.title':'Animació musical amb DJ ROXELL',
    'featured.fireworks.title':'Focs artificials', 'featured.fireworks.date':'Diumenge 6 · 24:00 h', 'featured.family.title':'Dia de la família', 'featured.family.date':'Dissabte 5 · 12:00 h', 'featured.race.title':'Cursa popular', 'featured.race.date':'Diumenge 6 · 09:00 h', 'featured.guard.title':'Concert de la Guàrdia Reial', 'featured.guard.date':'Diumenge 6 · 20:00 h', 'featured.stew.title':'Caldereta de daina', 'featured.stew.date':'Diumenge 6 · 14:00 h',
  },
  eu: {
    'incident.emergencyTitle':'Larrialdiak:', 'incident.emergencyCopy':'pertsonentzat edo ondasunentzat berehalako arriskua badago, deitu 112 zenbakira.', 'incident.emergencyBefore':'pertsonentzat edo ondasunentzat berehalako arriskua badago, deitu ', 'incident.emergencyAfter':' zenbakira.',
    'common.homeLink':'Jaietako hasierara itzuli', 'common.backToSite':'Itzuli webgunera', 'common.backToParticipate':'Itzuli Parte hartzera', 'common.other':'Beste bat', 'common.location':'Auzoa edo eremua', 'common.email':'Posta elektronikoa', 'common.privacyInfo':'pribatutasun informazioa',
    'idea.eyebrow':'Zure proposamena', 'idea.title':'Proposatu zure ideia', 'idea.description':'Partekatu Fuencarral–El Pardo hobetzeko proposamen zehatz bat. Udal taldeak baloratzeko jasoko du.', 'idea.fieldTitle':'Proposamenaren izenburua', 'idea.titlePlaceholder':'Adib.: Itzal gehiago plazan', 'idea.area':'Arloa', 'idea.selectArea':'Hautatu arlo bat', 'idea.publicSpace':'Espazio publikoa', 'idea.culture':'Kultura eta aisialdia', 'idea.mobility':'Mugikortasuna', 'idea.environment':'Ingurumena', 'idea.youth':'Haurtzaroa eta gazteria', 'idea.tellUs':'Kontatu zure ideia', 'idea.descriptionPlaceholder':'Azaldu zer proposatzen duzun, non izango lukeen eragina eta zergatik litzatekeen erabilgarria.', 'idea.emailOptional':'(aukerakoa, erantzuna nahi baduzu soilik)', 'idea.consentBefore':' ', 'idea.consentAfter':' irakurri dut eta nire proposamenaren tratamendua onartzen dut.', 'idea.submit':'Proposamena bidali',
    'incident.eyebrow':'Jakinarazi gorabehera bat', 'incident.title':'Gorabeherak', 'incident.description':'Adierazi auzoan aurkitzen dituzun arazoak berrikusi ahal izateko. Ez erabili kanal hau larrialdietarako: deitu 112 zenbakira.', 'incident.emergency':'Larrialdiak: pertsonentzat edo ondasunentzat berehalako arriskua badago, deitu 112 zenbakira.', 'incident.type':'Gorabehera mota', 'incident.selectCategory':'Hautatu kategoria bat', 'incident.cleaning':'Garbiketa', 'incident.lighting':'Argiteria', 'incident.road':'Bide publikoa', 'incident.furniture':'Hiri altzariak', 'incident.green':'Berdeguneak', 'incident.noise':'Zarata', 'incident.location':'Kokapena', 'incident.locationPlaceholder':'Kalea, plaza edo erreferentzia puntua', 'incident.describe':'Deskribatu gorabehera', 'incident.descriptionPlaceholder':'Azaldu zer gertatzen den eta hura aurkitzen laguntzeko xehetasunak gehitu.', 'incident.emailOptional':'(aukerakoa, erantzuna behar baduzu soilik)', 'incident.consentBefore':' ', 'incident.consentAfter':' irakurri dut eta gorabehera honen tratamendua onartzen dut.', 'incident.submit':'Gorabehera bidali',
    'brand.district':'Barrutia', 'language.label':'Hizkuntza', 'nav.home':'Hasiera', 'nav.fiestas':'Jaiak', 'nav.events':'Ekitaldiak', 'nav.map':'Mapa', 'nav.participate':'Parte hartu', 'nav.program':'Programa',
    'hero.dates':'abuztuak 29 — irailak 6, 2026', 'hero.title':'Bederatzi egun tradizioz, musikaz eta alaitasunez', 'hero.copy':'El Pardo berriro ezagutu: familiarekin, lagunekin eta auzo osoarekin gozatzeko jarduerak.', 'hero.events':'Ikusi ekitaldiak', 'hero.map':'Nola iritsi', 'countdown.copy':'Falta direnak jaien hasierarako', 'countdown.days':'egun',
    'programme.label':'Agenda nagusia', 'programme.title':'Egunetako programa', 'programme.download':'Programa deskargatu', 'programme.more':'Informazio gehiago', 'featured.label':'Plan bakoitzerako hitzordua', 'featured.title':'Ez galdu…',
    'events.label':'Kontsultatu programa', 'events.title':'Ekitaldi guztiak', 'events.count':'44 jarduera', 'events.filters':'Programaren iragazkiak', 'events.searchLabel':'Ekitaldiak bilatu', 'events.searchPlaceholder':'Ekitaldiak bilatu…', 'events.filterByCategory':'Kategoriaren arabera iragazi', 'events.empty':'Ez dago bilaketarekin bat datorren jarduerarik.',
    'map.label':'Aurkitu jarduera bakoitza', 'map.title':'Non izango dira jarduerak?', 'map.copy':'Kontsultatu mapan jaiak egingo diren espazio guztiak, lorategietatik Real Sitioko plazetara eta karpetara.', 'map.open':'Mapa ireki',
    'about.label':'El Pardo komunitatea da', 'about.title':'Pardeño maiteok', 'about.copyOne':'Real Sitioko jaiek musika, kultura, kirola eta gure barrutiari bizia ematen dioten tradizioez gozatzeko elkartzen gaituzte.', 'about.copyTwo':'Elkarteen, erakundeen eta auzotarren lankidetzari esker, adin guztietarako pentsatutako programa ospatzen dugu.',
    'participate.label':'Zure iritziak balio du', 'participate.title':'Parte hartu', 'participate.copy':'Lagundu barrutia hobetzen jarraitzeko.', 'card.survey':'Inkesta ofiziala', 'card.surveyCopy':'Partekatu jaiei buruzko zure iritzia.', 'card.idea':'Proposatu zure ideia', 'card.ideaCopy':'Partekatu barrutia hobetzeko proposamenak.', 'card.incident':'Gorabeherak', 'card.incidentCopy':'Jakinarazi zure auzoko gorabeherak erraz.',
    'qr.label':'Inkesta ofiziala', 'qr.title':'Erantzun mugikorretik', 'qr.copy':'Eskaneatu QR kodea El Pardoko jaien inkesta ofiziala irekitzeko.', 'qr.open':'Google inkesta ireki', 'footer.tagline':'Zure barrutia, zure komunitatea.', 'footer.legalLinks':'Legezko estekak', 'footer.contact':'Harremana', 'footer.legal':'Lege oharra', 'footer.privacy':'Pribatutasuna', 'footer.accessibility':'Irisgarritasuna',
    'category.Todos':'Guztiak', 'category.Música':'Musika', 'category.Infantil':'Haurrentzat', 'category.Deportes':'Kirolak', 'category.Tradición':'Tradizioa', 'category.Cultura':'Kultura', 'category.Gastronomía':'Gastronomia', 'weekday.Sábado':'Larunbata', 'weekday.Domingo':'Igandea', 'weekday.Lunes':'Astelehena', 'weekday.Martes':'Asteartea', 'weekday.Miércoles':'Asteazkena', 'weekday.Jueves':'Osteguna', 'weekday.Viernes':'Ostirala', 'month.Agosto':'Abuztua', 'month.Septiembre':'Iraila',
    'event.dardos.title':'Dardo txapelketa', 'event.disco.title':'Diskoteka mugikorra', 'event.pregón.title':'Jaietako pregoia', 'event.orquesta.title':'Tierra orkestra', 'event.carrera.title':'Herri lasterketa', 'event.chocolate.title':'Txokolatada herrikoia', 'event.visita.title':'Bisita gidatua: Emilio Carrère', 'event.chapas.title':'Haurrentzako txapa txapelketa', 'event.procesión.title':'Prozesio solemnea', 'event.gincana.title':'Ohiko jolasekin gymkhana', 'event.chinchon.title':'Chinchón txapelketa', 'event.roxell.title':'Musika animazioa DJ ROXELLekin',
    'featured.fireworks.title':'Su artifizialak', 'featured.fireworks.date':'Igandea 6 · 24:00 h', 'featured.family.title':'Familia eguna', 'featured.family.date':'Larunbata 5 · 12:00 h', 'featured.race.title':'Herri lasterketa', 'featured.race.date':'Igandea 6 · 09:00 h', 'featured.guard.title':'Errege Guardiaren kontzertua', 'featured.guard.date':'Igandea 6 · 20:00 h', 'featured.stew.title':'Oreinen gisatua', 'featured.stew.date':'Igandea 6 · 14:00 h',
  },
  gl: {
    'incident.emergencyTitle':'Urxencias:', 'incident.emergencyCopy':'se existe perigo inmediato para persoas ou bens, chama ao 112.', 'incident.emergencyBefore':'se existe perigo inmediato para persoas ou bens, chama ao ', 'incident.emergencyAfter':'.',
    'common.homeLink':'Volver ao inicio das festas', 'common.backToSite':'Volver á web', 'common.backToParticipate':'Volver a Participa', 'common.other':'Outro', 'common.location':'Barrio ou zona', 'common.email':'Correo electrónico', 'common.privacyInfo':'información de privacidade',
    'idea.eyebrow':'A túa proposta', 'idea.title':'Propón a túa idea', 'idea.description':'Comparte unha proposta concreta para mellorar Fuencarral–El Pardo. O equipo municipal recibiraa para a súa valoración.', 'idea.fieldTitle':'Título da proposta', 'idea.titlePlaceholder':'Ex.: Máis sombra na praza', 'idea.area':'Área', 'idea.selectArea':'Selecciona unha área', 'idea.publicSpace':'Espazo público', 'idea.culture':'Cultura e ocio', 'idea.mobility':'Mobilidade', 'idea.environment':'Medio ambiente', 'idea.youth':'Infancia e xuventude', 'idea.tellUs':'Cóntanos a túa idea', 'idea.descriptionPlaceholder':'Describe o que propós, onde tería impacto e por que sería útil.', 'idea.emailOptional':'(opcional, só se queres resposta)', 'idea.consentBefore':'Lin a ', 'idea.consentAfter':' e consinto o tratamento da miña proposta.', 'idea.submit':'Enviar proposta',
    'incident.eyebrow':'Comunica unha incidencia', 'incident.title':'Incidencias', 'incident.description':'Indica os problemas que atopes no barrio para que poidan revisarse. Non uses esta canle para urxencias: chama ao 112.', 'incident.emergency':'Urxencias: se existe perigo inmediato para persoas ou bens, chama ao 112.', 'incident.type':'Tipo de incidencia', 'incident.selectCategory':'Selecciona unha categoría', 'incident.cleaning':'Limpeza', 'incident.lighting':'Iluminación', 'incident.road':'Vía pública', 'incident.furniture':'Mobiliario urbano', 'incident.green':'Zonas verdes', 'incident.noise':'Ruído', 'incident.location':'Localización', 'incident.locationPlaceholder':'Rúa, praza ou punto de referencia', 'incident.describe':'Describe a incidencia', 'incident.descriptionPlaceholder':'Explica o que ocorre e engade detalles que axuden a localizala.', 'incident.emailOptional':'(opcional, só se precisas resposta)', 'incident.consentBefore':'Lin a ', 'incident.consentAfter':' e consinto o tratamento desta incidencia.', 'incident.submit':'Enviar incidencia',
    'brand.district':'Distrito', 'language.label':'Idioma', 'nav.home':'Inicio', 'nav.fiestas':'Festas', 'nav.events':'Eventos', 'nav.map':'Mapa', 'nav.participate':'Participa', 'nav.program':'Programa',
    'hero.dates':'29 agosto — 6 setembro 2026', 'hero.title':'Nove días de tradición, música e alegría', 'hero.copy':'Volta atoparte con El Pardo: actividades para gozar en familia, con amizades e con todo o barrio.', 'hero.events':'Ver eventos', 'hero.map':'Como chegar', 'countdown.copy':'Faltan para o inicio das festas', 'countdown.days':'días',
    'programme.label':'Axenda principal', 'programme.title':'Programa por días', 'programme.download':'Descargar programa', 'programme.more':'Máis información', 'featured.label':'Unha cita para cada plan', 'featured.title':'Non o perdas…',
    'events.label':'Consulta o programa', 'events.title':'Todos os eventos', 'events.count':'44 actividades', 'events.filters':'Filtros do programa', 'events.searchLabel':'Buscar eventos', 'events.searchPlaceholder':'Buscar eventos…', 'events.filterByCategory':'Filtrar por categoría', 'events.empty':'Non hai actividades que coincidan coa busca.',
    'map.label':'Atopa cada actividade', 'map.title':'Onde serán as actividades?', 'map.copy':'Consulta no mapa todos os espazos onde se celebrarán as festas, desde os xardíns ata as prazas e carpas do Real Sitio.', 'map.open':'Abrir o mapa',
    'about.label':'El Pardo é comunidade', 'about.title':'Queridos pardeños', 'about.copyOne':'As Festas do Real Sitio reúnennos para gozar da música, a cultura, o deporte e as tradicións que dan vida ao noso distrito.', 'about.copyTwo':'Grazas á colaboración de asociacións, entidades e veciñanza, celebramos un programa pensado para todas as idades.',
    'participate.label':'A túa opinión conta', 'participate.title':'Participa', 'participate.copy':'Axúdanos a seguir mellorando o distrito.', 'card.survey':'Enquisa oficial', 'card.surveyCopy':'Comparte a túa opinión sobre as festas.', 'card.idea':'Propón a túa idea', 'card.ideaCopy':'Comparte propostas para mellorar o distrito.', 'card.incident':'Incidencias', 'card.incidentCopy':'Comunica incidencias no teu barrio facilmente.',
    'qr.label':'Enquisa oficial', 'qr.title':'Responde desde o móbil', 'qr.copy':'Escanea o código QR para abrir a enquisa oficial das festas de El Pardo.', 'qr.open':'Abrir enquisa de Google', 'footer.tagline':'O teu distrito, a túa comunidade.', 'footer.legalLinks':'Ligazóns legais', 'footer.contact':'Contacto', 'footer.legal':'Aviso legal', 'footer.privacy':'Privacidade', 'footer.accessibility':'Accesibilidade',
    'category.Todos':'Todos', 'category.Música':'Música', 'category.Infantil':'Infantil', 'category.Deportes':'Deportes', 'category.Tradición':'Tradición', 'category.Cultura':'Cultura', 'category.Gastronomía':'Gastronomía', 'weekday.Sábado':'Sábado', 'weekday.Domingo':'Domingo', 'weekday.Lunes':'Luns', 'weekday.Martes':'Martes', 'weekday.Miércoles':'Mércores', 'weekday.Jueves':'Xoves', 'weekday.Viernes':'Venres', 'month.Agosto':'Agosto', 'month.Septiembre':'Setembro',
    'event.dardos.title':'Torneo de dardos', 'event.disco.title':'Discoteca móbil', 'event.pregón.title':'Pregón das festas', 'event.orquesta.title':'Orquestra Tierra', 'event.carrera.title':'Carreira popular', 'event.chocolate.title':'Chocolatada popular', 'event.visita.title':'Visita guiada: Emilio Carrère', 'event.chapas.title':'Torneo infantil de chapas', 'event.procesión.title':'Procesión solemne', 'event.gincana.title':'Xincana con xogos tradicionais', 'event.chinchon.title':'Torneo de chinchón', 'event.roxell.title':'Animación musical con DJ ROXELL',
    'featured.fireworks.title':'Fogos artificiais', 'featured.fireworks.date':'Domingo 6 · 24:00 h', 'featured.family.title':'Día da familia', 'featured.family.date':'Sábado 5 · 12:00 h', 'featured.race.title':'Carreira popular', 'featured.race.date':'Domingo 6 · 09:00 h', 'featured.guard.title':'Concerto da Garda Real', 'featured.guard.date':'Domingo 6 · 20:00 h', 'featured.stew.title':'Caldereta de gamo', 'featured.stew.date':'Domingo 6 · 14:00 h',
  },
  en: {
    'incident.emergencyTitle':'Emergencies:', 'incident.emergencyCopy':'if there is immediate danger to people or property, call 112.', 'incident.emergencyBefore':'if there is immediate danger to people or property, call ', 'incident.emergencyAfter':'.',
    'common.homeLink':'Back to the festival home page', 'common.backToSite':'Back to the website', 'common.backToParticipate':'Back to Take part', 'common.other':'Other', 'common.location':'Neighbourhood or area', 'common.email':'Email address', 'common.privacyInfo':'privacy information',
    'idea.eyebrow':'Your proposal', 'idea.title':'Share your idea', 'idea.description':'Share a specific suggestion to improve Fuencarral–El Pardo. The municipal team will receive it for review.', 'idea.fieldTitle':'Proposal title', 'idea.titlePlaceholder':'E.g. More shade in the square', 'idea.area':'Area', 'idea.selectArea':'Select an area', 'idea.publicSpace':'Public space', 'idea.culture':'Culture and leisure', 'idea.mobility':'Mobility', 'idea.environment':'Environment', 'idea.youth':'Children and young people', 'idea.tellUs':'Tell us your idea', 'idea.descriptionPlaceholder':'Describe what you propose, where it would have an impact and why it would be useful.', 'idea.emailOptional':'(optional, only if you would like a reply)', 'idea.consentBefore':'I have read the ', 'idea.consentAfter':' and consent to the processing of my proposal.', 'idea.submit':'Send proposal',
    'incident.eyebrow':'Report an issue', 'incident.title':'Issues', 'incident.description':'Tell us about problems you find in the neighbourhood so they can be reviewed. Do not use this channel for emergencies: call 112.', 'incident.emergency':'Emergencies: if there is immediate danger to people or property, call 112.', 'incident.type':'Issue type', 'incident.selectCategory':'Select a category', 'incident.cleaning':'Cleaning', 'incident.lighting':'Street lighting', 'incident.road':'Public highway', 'incident.furniture':'Street furniture', 'incident.green':'Green spaces', 'incident.noise':'Noise', 'incident.location':'Location', 'incident.locationPlaceholder':'Street, square or landmark', 'incident.describe':'Describe the issue', 'incident.descriptionPlaceholder':'Explain what is happening and add details to help locate it.', 'incident.emailOptional':'(optional, only if you need a reply)', 'incident.consentBefore':'I have read the ', 'incident.consentAfter':' and consent to the processing of this issue.', 'incident.submit':'Send issue',
    'brand.district':'District', 'language.label':'Language', 'nav.home':'Home', 'nav.fiestas':'Festival', 'nav.events':'Events', 'nav.map':'Map', 'nav.participate':'Take part', 'nav.program':'Programme',
    'hero.dates':'29 August — 6 September 2026', 'hero.title':'Nine days of tradition, music and joy', 'hero.copy':'Meet El Pardo again: activities to enjoy with family, friends and the whole neighbourhood.', 'hero.events':'View events', 'hero.map':'Getting here', 'countdown.copy':'Days until the festival begins', 'countdown.days':'days',
    'programme.label':'Main agenda', 'programme.title':'Daily programme', 'programme.download':'Download programme', 'programme.more':'More information', 'featured.label':'Something for every plan', 'featured.title':'Don’t miss…',
    'events.label':'Browse the programme', 'events.title':'All events', 'events.count':'44 activities', 'events.filters':'Programme filters', 'events.searchLabel':'Search events', 'events.searchPlaceholder':'Search events…', 'events.filterByCategory':'Filter by category', 'events.empty':'No activities match your search.',
    'map.label':'Find every activity', 'map.title':'Where will the activities take place?', 'map.copy':'Use the map to find every festival space, from gardens to the squares and marquees of the Royal Site.', 'map.open':'Open map',
    'about.label':'El Pardo is community', 'about.title':'Dear residents of El Pardo', 'about.copyOne':'The Royal Site Festival brings us together to enjoy the music, culture, sport and traditions that bring our district to life.', 'about.copyTwo':'Thanks to the collaboration of associations, organisations and residents, we celebrate a programme designed for all ages.',
    'participate.label':'Your opinion matters', 'participate.title':'Take part', 'participate.copy':'Help us keep improving the district.', 'card.survey':'Official survey', 'card.surveyCopy':'Share your opinion about the festival.', 'card.idea':'Share your idea', 'card.ideaCopy':'Share suggestions to improve the district.', 'card.incident':'Report an issue', 'card.incidentCopy':'Easily report issues in your neighbourhood.',
    'qr.label':'Official survey', 'qr.title':'Respond from your phone', 'qr.copy':'Scan the QR code to open the official El Pardo Festival survey.', 'qr.open':'Open Google survey', 'footer.tagline':'Your district, your community.', 'footer.legalLinks':'Legal links', 'footer.contact':'Contact', 'footer.legal':'Legal notice', 'footer.privacy':'Privacy', 'footer.accessibility':'Accessibility',
    'category.Todos':'All', 'category.Música':'Music', 'category.Infantil':'Children', 'category.Deportes':'Sports', 'category.Tradición':'Tradition', 'category.Cultura':'Culture', 'category.Gastronomía':'Food & drink', 'weekday.Sábado':'Saturday', 'weekday.Domingo':'Sunday', 'weekday.Lunes':'Monday', 'weekday.Martes':'Tuesday', 'weekday.Miércoles':'Wednesday', 'weekday.Jueves':'Thursday', 'weekday.Viernes':'Friday', 'month.Agosto':'August', 'month.Septiembre':'September',
    'event.dardos.title':'Darts tournament', 'event.disco.title':'Mobile disco', 'event.pregón.title':'Festival proclamation', 'event.orquesta.title':'Tierra Orchestra', 'event.carrera.title':'Community race', 'event.chocolate.title':'Community hot chocolate', 'event.visita.title':'Guided tour: Emilio Carrère', 'event.chapas.title':'Children’s bottle-cap tournament', 'event.procesión.title':'Solemn procession', 'event.gincana.title':'Traditional games gymkhana', 'event.chinchon.title':'Chinchón tournament', 'event.roxell.title':'Music entertainment with DJ ROXELL',
    'featured.fireworks.title':'Fireworks', 'featured.fireworks.date':'Sunday 6 · 24:00 h', 'featured.family.title':'Family day', 'featured.family.date':'Saturday 5 · 12:00 h', 'featured.race.title':'Community race', 'featured.race.date':'Sunday 6 · 09:00 h', 'featured.guard.title':'Royal Guard concert', 'featured.guard.date':'Sunday 6 · 20:00 h', 'featured.stew.title':'Fallow deer stew', 'featured.stew.date':'Sunday 6 · 14:00 h',
  },
};

function textFor(language: Language, key: string, original: string) {
  return language === 'es' ? original : translations[language][key] ?? original;
}

function translateAttribute(language: Language, selector: string, attribute: 'placeholder' | 'aria-label', dataAttribute: 'i18nPlaceholder' | 'i18nAriaLabel') {
  document.querySelectorAll<HTMLElement>(selector).forEach((element) => {
    const key = element.dataset[dataAttribute];
    if (!key) return;
    const defaultKey = `${dataAttribute}Default` as keyof DOMStringMap;
    const original = element.dataset[defaultKey] ?? element.getAttribute(attribute) ?? '';
    element.dataset[defaultKey] = original;
    element.setAttribute(attribute, textFor(language, key, original));
  });
}

export function applyLanguage(language: Language) {
  document.documentElement.lang = language;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((element) => {
    const key = element.dataset.i18n!;
    const original = element.dataset.i18nDefault ?? element.textContent ?? '';
    element.dataset.i18nDefault = original;
    element.textContent = textFor(language, key, original);
  });
  translateAttribute(language, '[data-i18n-placeholder]', 'placeholder', 'i18nPlaceholder');
  translateAttribute(language, '[data-i18n-aria-label]', 'aria-label', 'i18nAriaLabel');
  window.localStorage.setItem('el-pardo-language', language);
}

export function savedLanguage(): Language {
  const value = window.localStorage.getItem('el-pardo-language');
  return value === 'ca' || value === 'eu' || value === 'gl' || value === 'en' ? value : 'es';
}
